# Metadata for this specific system configuration preset

config_version = 1

# Name of the system; used internally to reference it and for paths, etc.
name = "template"

# Full "pretty" name of the system, e.g. for UI text
name_full = "Mjolnir Config Template System"
# Freeform description of the system's author
author = "Your name here"
# Freeform description of the system's intended function and purpose
description = "System configuration for the template package"
# Official website for this specific system
homepage = "https://www.example.com"
# Repository containing the system's source code
repo = "https://github.com"
# SPDX license identifier for the this configuration package (CC0/PD)
license = "CC0-1.0"

# Version of the config package; should follow SemVer and PEP 396
version = "0.1.0"
# Minimum Brokkr version this version of the config package needs to work
brokkr_version_min = "0.3.0"
# As above, but maximum version (e.g. "0.3.99" for < 0.4.x)
brokkr_version_max = ""
# Ibid, for Sindri
sindri_version_min = "0.3.0"
sindri_version_max = ""
