# Metadata for this specific system configuration preset

config_version = 1

name = "template"

# Full "pretty" name of the system, e.g. for UI text
name_full = "Mjolnir Config Template System"
# Freeform description of the system's author
author = "Your name here"
# Freeform description of the system's intended function and purpose
description = "System configuration for the template package"
# Website where visitors can learn more about the system or view the data
homepage = "https://www.example.com"
# Repository containing the system's source code
repo = "https://github.com"

# Version of the config package; should follow SemVer and PEP 396
version = "0.1.0"
# Minimun Brokkr version this version of the config package needs to work
brokkr_version_min = "0.3.0"
# Ibid, for Sindri
sindri_version_min = "0.3.0"
