# Example ultra-minimal device preset demonstrating a sample transform preset
config_version = 1
name = "example_transform_minimal"

[transforms]
    [transforms.alerts]
        _module_path = "example_transform_minimal"
        _class_name = "ExampleTransformPlugin"
        _is_plugin = true
        name = "Example TransformStep Alert Plugin"
