# Example device preset demonstrating a sample output preset

config_version = 1
# Name of this device preset, used for lookup
name = "example_output"
# Type of this preset; currently the only type is device
type = "device"
# Dependencies required by all inputs in this device preset
_dependencies = [ "brokkr>=0.3.0" ]

# Preset-level metadata; format follows that specified in the top-level
[metadata]
    name_full = "Example Output Preset"
    author = "Your name here"
    description = "Long description here"
    homepage = "https://www.example.com"
    repo = "https://github.com"
    preset_version = "0.1.0"
    brokkr_version_min = "0.3.0"
    brokkr_version_max = ""

[outputs]
    # Preset that outputs data in Tab-Separated Value (TSV) format
    [outputs.tsv_file]
        _module_path = "brokkr.outputs.csvfile"
        _class_name = "CSVFileOutput"
        # Dependencies required by this specific item
        _dependencies = []
        csv_kwargs.delimiter = "\t"
        extension = "tsv"
        name = "TSV File Output"
        output_path = "data"

    # An example preset that showcases using a plugin
    [outputs.repr_file]
        _module_path = "example_output"
        _class_name = "ExampleFileOutput"
        _is_plugin = true
        # Dependencies required by this specific item
        _dependencies = []
        name = "Example File Output Plugin"
        extension = "txt"
