# Example minimal device preset demonstrating a sample output preset
config_version = 1
name = "example_output_minimal"

[outputs]
    [outputs.reprfile]
        _module_path = "example_output_minimal"
        _class_name = "ExampleFileOutput"
        _is_plugin = true
        name = "Example File Output Plugin"
        extension = "txt"
