# Example minimal device preset demonstrating a sensor input preset
config_version = 1
name = "example_input_sensor_minimal"

[data_types]
    example_sensor_temperature = { full_name = "Temperature (Example)", custom_attrs.attribute_name = "temperature", digits = 3 }
    example_sensor_pressure = { full_name = "Pressure (Example)", binary_type = "f", unit = "hPa", uncertainty = 1.0, custom_attrs.attribute_name = "pressure", digits = 3 }
    example_sensor_humidity = { full_name = "Humidity (Example)", binary_type = "f", unit = "%", uncertainty = 3.0, custom_attrs.attribute_name = "humidity", digits = 3 }

[inputs]
    [inputs.sensor_method]
        _module_path = "example_input_sensor"
        _class_name = "ExampleSensorPropertyInput"
        _is_plugin = true
        sensor_kwargs.attribute_dict = { temperature = 25, pressure = 1013, humidity = 50 }
        sensor_kwargs.as_methods = true
        data_types = [ "example_sensor_temperature", "example_sensor_pressure", "example_sensor_humidity" ]
