# Example preset demonstrating a sample configuration setup

config_version = 1
# Name of this device preset, used for lookup
name = "example"
# Type of this preset; currently the only type is device
type = "device"
# Dependencies required by all inputs in this device preset
_dependencies = [ "brokkr>=0.3.0" ]

# Preset-level metadata; format follows that specified in the top-level
[metadata]
name_full = "Example Preset"
author = "Your name here"
description = "Long description here"
homepage = "https://www.example.com"
repo = "https://github.com"
preset_version = "0.1.0"
brokkr_version_min = "0.3.0"

# Data type presets to use for the data types that follow
[type_presets]
timestamp = { binary_type = "q", conversion = "time_posix_ms", unit = "s", uncertainty = 0.001}

# Data types referenced in individual presets
[data_types]
timestamp_main = { full_name = "Time Stamp", type_presets = "timestamp" }
example_volts = { binary_type = "f", conversion = "custom", scale = 20, digits = 3, unit = "V", uncertainty = 0.1, na_marker = -999 }
example_time = { binary_type = "f", conversion = "custom", base = 10, power = 9, after = "time_posix", unit = "s", uncertainty = 1 }
example_str = { binary_type = "s", conversion = "str" }

# By convention, presets are categorized into "input", "output", "commands", etc.

# A simple input preset that pings localhost
[inputs.ping]
# Module to load with the class to use
_module_path = "brokkr.inputs.ping"
# PipelineStep class to instantiate with the preset's data
_class_name = "PingInput"
# Name of the step, used for UI text and logging
name = "Ping Localhost"
# Step-specific parameters
host = "127.0.0.1"
timeout_s = 1

# An example preset that parses a timestamp from a heatbeat UDP packet
[inputs.timestamp]
_module_path = "brokkr.inputs.udp"
_class_name = "UDPInput"
name = "Example UDP packet with timestamp"
host = "127.0.0.1"
port = 8080
timeout_s = 2
data_types = [
    "timestamp_main",
]

# An example preset that showcases using a plugin
[inputs.plugin]
_module_path = "example"
_class_name = "ExamplePluginInput"
_is_plugin = true
# Dependencies required by this specific item
_dependencies = [ "toml" ]
name = "Example Plugin"
na_chance = 0.2
data_types = [
    "example_volts",
    "example_time",
    "example_str",
]
